version: '3.5'

services:
  backend:
    build: 
      context: ./backend/app
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - MONGO_USER=admin
      - MONGO_PASS=bn1Dd5DqLFkWHFOY
      - MONGO_DB=planning_poker
      - BROADCAST_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379